### ISSUE TITLE
Synchronize All button takes ages

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-registry#50]
the rest endpoint via curl
time curl -X PUT "http://intermine-registry.herokuapp.com/service/synchronize" -H "accept: application/json" -H  "authorization: Basic....."
takes about 15sec

**Comment by lkuffo** [comment]
This problem was caused because there was no timeout parameter when doing fetch to the different endpoints. So, if one endpoint didn't work, the registry will just continue trying to fetch for a long amount of time, therefore never advancing with other mines.  

It should be solved. However, i didn't have the opportunity to test the fix. We need a mine to not be running to test it.
