### ISSUE TITLE
World view map only shows one instance if there are 2 with the same locations

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-registry#55]
See FlyMine and HumanMine: they have same locations but instances world only shows one

**Comment by lkuffo** [comment]
Doing some research, I've detected that this is not registry bug at all. What happened was that Human Mine and Fly Mine didn't have the exact same latitude/longitude coordinates. They were different parting from the sixth decimal place. In practice they were the same location (these decimals represent just millimeters of difference), but numerically they were different. So the registry makes two different markers, but since their positions are just different by millimeters, both markers are in the exact same position in the map. 

Fixed by updating the locations of one of them (HumanMine) to be exactly equal the other (FlyMine).
